openflighthpc/openflight-omnibus-builder

README.md, scripts/promote-rpm.sh, scripts/promote-rpms.sh, scripts/publish-rpm.sh, scripts/publish-rpms.sh
=> Scripts for pushing to yum repos

builders/flight-desktop/Gemfile.lock, builders/flight-desktop/config/projects/flight-desktop.rb, builders/flight-desktop/config/software/flight-desktop.rb, builders/flight-desktop/config/software/flight-runway.rb, builders/flight-desktop/opt/flight/libexec/commands/desktop, builders/flight-env/Gemfile.lock, builders/flight-env/config/projects/flight-env.rb, builders/flight-env/config/software/flight-env.rb, builders/flight-env/config/software/flight-runway.rb, builders/flight-env/opt/flight/etc/banner/tips.d/10-env.rc, builders/flight-env/opt/flight/etc/env.cshrc, builders/flight-env/opt/flight/etc/env.rc, builders/flight-env/opt/flight/etc/profile.d/10-env.csh, builders/flight-env/opt/flight/etc/profile.d/10-env.sh, builders/flight-env/opt/flight/libexec/commands/env, builders/flight-runway/Gemfile.lock, builders/flight-runway/config/projects/flight-runway.rb, builders/flight-runway/config/software/flight-runway.rb, builders/flight-runway/config/software/ruby.rb, builders/flight-starter/build.sh, builders/flight-starter/rpm/flight-starter.spec, builders/flight-user-suite/flight-user-suite.spec, scripts/promote-rpms.sh, scripts/publish-rpms.sh, vagrant/provision.sh
This PR prepares omnibus for major version increases in runway, starter, env and desktop for the 2020.2 release of Flight User Suite.
=> Flight User Suite 2020.2 Release

scripts/promote-rpm.sh, scripts/promote-rpms.sh, scripts/publish-rpm.sh, scripts/publish-rpms.sh, scripts/slack-check.sh, scripts/slack-update.sh
This PR adds in scripts for handling notifications to the #openflight slack channel on successful publish/promote of an RPM.
=> Update Slack on Package Publish/Promotion

builders/flight-action-api-estate/config/projects/flight-action-api-estate.rb, builders/flight-action-api-estate/config/software/flight-action-api-estate.rb, builders/flight-action-api-estate/opt/flight/opt/action-api/libexec/estate-grow/keys.conf, builders/flight-action-api/config/projects/flight-action-api.rb, builders/flight-action-api/opt/flight/etc/www/server-https.d/flight-action-api.conf, builders/flight-action-api/opt/flight/libexec/commands/action-api
=> Rolling PR for flight-action-api (server) version 1.2.0

builders/flight-action/config/projects/flight-action.rb, builders/flight-action/opt/flight/libexec/commands/action
=> Rolling PR for flight-action (client) version 1.2.0

builders/flight-www/config/projects/flight-www.rb, builders/flight-www/package-scripts/flight-www/postinst
Also move the cron renewal from daily to weekly
=> Add a warning that the config file has changed

builders/flight-action-api-estate/config/projects/flight-action-api-estate.rb, builders/flight-action-api-estate/config/software/flight-action-api-estate.rb, builders/flight-action-api-estate/package-scripts/flight-action-api-estate/postinst, builders/flight-action-api/config/projects/flight-action-api.rb, builders/flight-action-api/opt/flight/libexec/commands/action-api, builders/flight-action/config/projects/flight-action.rb, builders/flight-action/opt/flight/libexec/commands/action
=> Rolling PR for flight-estate show and flight-action changes

builders/flight-action-api-estate/config/projects/flight-action-api-estate.rb, builders/flight-action-api-estate/config/software/flight-action-api-estate.rb, builders/flight-action-api-ipmi/.bundle/config, builders/flight-action-api-ipmi/.gitignore, builders/flight-action-api-ipmi/Gemfile, builders/flight-action-api-ipmi/Gemfile.lock, builders/flight-action-api-ipmi/LICENSE.txt, builders/flight-action-api-ipmi/README.md, builders/flight-action-api-ipmi/config/projects/flight-action-api-ipmi.rb, builders/flight-action-api-ipmi/config/software/flight-action-api-ipmi.rb, builders/flight-action-api-ipmi/omnibus.rb, builders/flight-action-api-ipmi/resources/flight-action-api-ipmi/rpm/spec.erb, builders/flight-action-api-power/config/projects/flight-action-api-power.rb, builders/flight-action-api/config/projects/flight-action-api.rb, builders/flight-action-api/config/software/flight-action-api.rb, builders/flight-action-api/opt/flight/etc/service/env/action-api, builders/flight-action-api/opt/flight/libexec/commands/action-api, builders/flight-ipmi/.bundle/config, builders/flight-ipmi/.gitignore, builders/flight-ipmi/Gemfile, builders/flight-ipmi/Gemfile.lock, builders/flight-ipmi/LICENSE.txt, builders/flight-ipmi/README.md, builders/flight-ipmi/config/projects/flight-ipmi.rb, builders/flight-ipmi/omnibus.rb, builders/flight-ipmi/opt/flight/libexec/commands/ipmi, builders/flight-ipmi/package-scripts/flight-action/postinst, builders/flight-ipmi/resources/flight-ipmi/deb/control.erb, builders/flight-ipmi/resources/flight-ipmi/rpm/spec.erb
=> Rolling PR for action-api azure and ipmi scripts

builders/flight-job-script-webapp/config/software/flight-job-script-webapp.rb
=> Fix flight-job-script-webapp intermittent build issue

builders/flight-howto/config/projects/flight-howto.rb, builders/flight-howto/opt/flight/libexec/commands/howto
=> Rolling PR for flight-howto 1.1.2

builders/flight-job-script-api/config/projects/flight-job-script-api.rb, builders/flight-job-script-api/config/software/flight-job-script-api.rb, builders/flight-job-script-api/opt/flight/etc/service/env/job-script-api, builders/flight-job-script-api/opt/flight/etc/service/types/job-script-api/reload.sh, builders/flight-job-script-api/opt/flight/etc/service/types/job-script-api/start.sh, builders/flight-job-script-api/opt/flight/etc/service/types/job-script-api/stop.sh, builders/flight-job-script-api/opt/flight/opt/job-script-api/bin/start, builders/flight-job-script-webapp/config/projects/flight-job-script-webapp.rb
=> Rolling changes for flight-job-script-api version 0.8.X

Vagrantfile, builders/flight-console-api/config/projects/flight-console-api.rb, builders/flight-console-api/opt/flight/opt/console-api/etc/config.json, builders/flight-console-api/package-scripts/flight-console-api/postinst, builders/flight-console-webapp/config/projects/flight-console-webapp.rb, builders/flight-desktop-webapp/config/projects/flight-desktop-webapp.rb, builders/flight-file-manager-api/config/projects/flight-file-manager-api.rb, builders/flight-file-manager-api/opt/flight/etc/service/types/file-manager-api/configure.sh, builders/flight-file-manager-webapp/config/projects/flight-file-manager-webapp.rb, builders/flight-login-api/config/projects/flight-login-api.rb, builders/flight-login-api/package-scripts/flight-login-api/postinst, builders/flight-www/config/projects/flight-www.rb, builders/flight-www/opt/flight/opt/www/bin/landing-page
Miscellaneous fixes for the web suite.
=> Web suite fixes

builders/flight-job-script-api/.gitignore, builders/flight-job-script-api/config/projects/flight-job-script-api.rb, builders/flight-job-script-api/config/software/flight-job-script-api.rb, builders/flight-job-script-webapp/config/projects/flight-job-script-webapp.rb
=> Rolling PR for flight-job-script-* version 0.10.X

builders/flight-job/config/projects/flight-job.rb, builders/flight-job/contrib/howto/2.1, builders/flight-job/opt/flight/libexec/commands/job
=> Rolling PR for flight-job version 2.1.X

builders/flight-job/config/projects/flight-job.rb, builders/flight-job/contrib/howto/2.1, builders/flight-job/opt/flight/libexec/commands/job
This is a sub-feature branch for the `2.1.0` release. It contains the `notes` and "script-name" related work.
=> Rolling PR for flight-job-2.1.0-dX releases

builders/flight-job/config/projects/flight-job.rb, builders/flight-job/contrib/howto/2.1, builders/flight-job/opt/flight/libexec/commands/job
=> Rolling PR for flight-job 2.1.x-f

builders/flight-job-script-api/config/projects/flight-job-script-api.rb
=> Rolling PR for flight-job-script-api-1.1.0

builders/flight-job/config/projects/flight-job.rb, builders/flight-job/opt/flight/libexec/commands/job
=> Rolling PR for flight-job 2.1.0-gX

builders/flight-job/config/projects/flight-job.rb, builders/flight-job/opt/flight/libexec/commands/job
=> Rolling PR for flight-job-2.1.0~hX

builders/flight-job/config/projects/flight-job.rb, builders/flight-job/opt/flight/libexec/commands/job
=> Rolling PR for flight-job-2.1.0-i

builders/flight-job/config/projects/flight-job.rb, builders/flight-job/config/software/flight-job.rb, builders/flight-job/contrib/howto/2.1, builders/flight-job/opt/flight/libexec/commands/job
=> Include flight-job state map and update howto guide

builders/flight-console-api/config/projects/flight-console-api.rb, builders/flight-console-webapp/config/projects/flight-console-webapp.rb
=> Rolling PR for flight-console working directory feature

builders/flight-starter/build.sh
=> Rolling PR for flight-starter 2021.2.2

builders/flight-job/config/projects/flight-job.rb, builders/flight-job/contrib/howto/2.2, builders/flight-job/opt/flight/libexec/commands/job
Bump `flight-job` to `2.2.0-dx`.  Replaces #119 and #121.
=> Job output and results

builders/flight-file-manager-api/config/projects/flight-file-manager-api.rb, builders/flight-file-manager-api/config/software/flight-file-manager-api.rb, builders/flight-file-manager-api/package-scripts/flight-file-manager-api/postinst, builders/flight-file-manager-webapp/config/projects/flight-file-manager-webapp.rb
=> Rolling PR for flight-file-manager-*-1.1.0-b

builders/flight-job-script-api/config/projects/flight-job-script-api.rb, builders/flight-job-script-webapp/config/projects/flight-job-script-webapp.rb, builders/flight-job/config/projects/flight-job.rb, builders/flight-job/opt/flight/libexec/commands/job
=> Rolling PR flight-job 2.2.0-eX and flight-job-script-api 1.2.0-cX

builders/flight-desktop-restapi/config/projects/flight-desktop-restapi.rb, builders/flight-desktop-restapi/config/software/flight-desktop-restapi.rb
=> Remove the .cli-version file from flight-desktop-restapi

builders/flight-www/dist/nginx.conf.tpl
=> Redirect 404 responses to /not-found

builders/flight-desktop-webapp/config/projects/flight-desktop-webapp.rb, builders/flight-desktop/config/projects/flight-desktop.rb
This way the sessions are always websockified
=> Add flight-websockify as a dependency to flight-desktop

builders/flight-desktop/contrib/howto/1.6
=> Update flight-desktop howto with --app and --script

.env, builders/flight-starter/deb/control.tpl, builders/flight-starter/rpm/flight-starter.spec, builders/flight-web-suite-utils/config/projects/flight-web-suite-utils.rb, builders/flight-web-suite-utils/config/software/flight-web-suite-utils.rb, builders/flight-web-suite-utils/omnibus.rb, builders/flight-web-suite-utils/opt/flight/libexec/commands/web-suite, builders/flight-web-suite/rpm/flight-web-suite.spec, share/config/software/enforce-flight-runway.rb
=> Package flight-web-suite CLI into flight-web-suite-utils

builders/flight-scheduler-controller/config/projects/flight-scheduler-controller.rb, builders/flight-scheduler-controller/package-scripts/flight-scheduler-controller/postinst, builders/flight-scheduler-controller/package-scripts/flight-scheduler-controller/prerm, builders/flight-scheduler-controller/resources/flight-scheduler-controller/rpm/spec.erb, builders/flight-scheduler-daemon/config/projects/flight-scheduler-daemon.rb, builders/flight-scheduler-daemon/package-scripts/flight-scheduler-daemon/prerm, builders/flight-scheduler-daemon/resources/flight-scheduler-daemon/rpm/spec.erb
=> Restart/stop flight-schedule-controller/daemon in package scripts

builders/flight-desktop/config/projects/flight-desktop.rb
=> Allow alpha builds of flight-desktop

builders/flight-python/config/projects/flight-python.rb, builders/flight-python/config/software/python.rb
=> Reduce the size of flight-python

builders/flight-desktop-restapi/config/projects/flight-desktop-restapi.rb, builders/flight-desktop/config/projects/flight-desktop.rb
=> Move the screen grabber dependencies to flight-desktop

builders/flight-console-api/opt/flight/etc/service/types/console-api/stop.sh
* `flight service stop console-api` now waits for console api to gracefully shutdown.
* `flight service stop console-api --force` will not wait for the graceful shutdown.  I.e., it will implement the current behaviour.  This requires an as yet unreleased version of `flight-service`.
=> Fix Console API graceful shutdown issues

builders/flight-profile-types/build.sh, builders/flight-profile-types/deb/control.tpl, builders/flight-profile-types/rpm/flight-profile-types.spec, builders/flight-profile/.bundle/config, builders/flight-profile/.gitignore, builders/flight-profile/Gemfile, builders/flight-profile/Gemfile.lock, builders/flight-profile/LICENSE.txt, builders/flight-profile/config/projects/flight-profile.rb, builders/flight-profile/config/software/enforce-flight-runway.rb, builders/flight-profile/config/software/flight-profile.rb, builders/flight-profile/omnibus.rb, builders/flight-profile/opt/flight/libexec/commands/profile, builders/flight-profile/resources/flight-profile/deb/control.erb, builders/flight-profile/resources/flight-profile/rpm/spec.erb
As title. This is the first release of profile and profile-types that I'm happy to draw a line under and merge into the main branch of our omnibus builder.
=> Create Flight Profile and Flight Profile Types builders

builders/flight-hunter/config/projects/flight-hunter.rb, builders/flight-hunter/opt/flight/libexec/commands/hunter
=> Bump Flight Hunter

builders/flight-profile-types/build.sh, builders/flight-profile-types/deb/control.tpl, builders/flight-profile-types/rpm/flight-profile-types.spec, builders/flight-profile/config/projects/flight-profile.rb, builders/flight-profile/opt/flight/libexec/commands/profile
- Flight Profile bumped to 0.2.0
- Flight Profile Types bumped to 0.2.0
=> Bump flight profile

Vagrantfile, builders/flight-env-types/build.sh, builders/flight-gather/README.md, builders/flight-hunter/config/projects/flight-hunter.rb, builders/flight-hunter/opt/flight/libexec/commands/hunter, builders/flight-profile-types/build.sh, builders/flight-profile/.bundle/config, builders/flight-profile/config/projects/flight-profile.rb, builders/flight-profile/opt/flight/libexec/commands/profile, builders/flight-silo/config/projects/flight-silo.rb, builders/flight-silo/config/software/flight-silo.rb, builders/flight-silo/opt/flight/libexec/commands/silo, builders/flight-starter/build.sh
- `flight-starter`: `2023.1.1`
- `flight-profile`: `0.3.0`
- `flight-profile-types`: `0.3.0`
- `flight-hunter`: `0.4.1`
- `flight-env-types`: `1.0.7`
- `flight-silo`: `0.1.0`
=> 16-06 releases

Vagrantfile, vagrant/provision.sh
This PR adds an Ubuntu 22.04 LTS build VM to the Vagrantfile. The logic to set up shared folders has been reused across machines.
=> Add Ubuntu 22.04 LTS build VM

builders/flight-hunter/opt/flight/etc/banner/banner.d/20-hunter-status.sh, builders/flight-hunter/opt/flight/etc/banner/tips.d/30-hunter.rc, builders/flight-hunter/opt/flight/etc/settings.d/hunter.rc, builders/flight-profile/config/projects/flight-profile.rb, builders/flight-profile/opt/flight/etc/banner/banner.d/21-profile-status.sh, builders/flight-profile/opt/flight/etc/banner/tips.d/40-profile.rc, builders/flight-profile/opt/flight/etc/settings.d/profile.rc
See: https://github.com/openflighthpc/openflight-omnibus-builder/pull/287
=>  Add Profile & Hunter to Banner & Tips

builders/flight-headnode-landing-page/config/software/flight-webapp-components.rb
Add configuration to load branding for login modal for flight landing page.
=> Add branding config to landing page login JS
