- builders/openflighthpc-release/openflighthpc-release.spec
- scripts/promote-rpms.sh
- scripts/publish-rpm.sh
- scripts/publish-rpms.sh
**This PR is for a WIP branch and should not yet be merged until fully tested and verified to be working**
Currently the omnibus publish & promote scripts for RPMs are hard-coded for x86_64. This PR aims to introduce complete architecture flexibility by utilising the RPM command to identify the architecture of built packages and to upload them to the correct locations.
The above should allow for the openflight repo to support multiple architectures.
> Add arm support

- builders/flight-desktop-client/config/projects/flight-desktop-client.rb
- builders/flight-desktop-client/opt/flight/etc/service/desktop-client/configuration.yml
- builders/flight-desktop-client/opt/flight/etc/service/desktop-client/configure.sh
- builders/flight-desktop-client/opt/flight/etc/service/desktop-client/metadata.yml
- builders/flight-desktop-client/package-scripts/flight-desktop-client/postinst
- builders/flight-service/config/projects/flight-service.rb
- builders/flight-service/config/software/flight-service.rb
Use `flight service configure` to configure `flight-desktop-client`.  The `configuration.yml` file assumes a version of `flight-service` including https://github.com/openflighthpc/flight-service/pull/4.
> Use flight service to configure desktop client

- builders/flight-service-www/opt/flight/bin/flight-service-www-https
- builders/flight-service-www/opt/flight/libexec/commands/www
- builders/flight-service-www/opt/flight/opt/www/bin/https
This PR adds a script to setup HTTPs for `flight-service-www`.  It 1) generates self-signed SSL certificates; 2) copies them to the correct location; 3) configures nginx to use HTTPs; and 4) restarts the `www` service.
The script is added to `/opt/flight/bin/` and is expected to be called as `flexec flight-service-www-https enable`.
I have a couple of questions regarding this:
1. Is the `/opt/flight/bin/` the correct location for this script?  Or should it be somewhere in `/opt/flight/libexec/`?
2. The certificate is valid for 365 days.  Do you have any reason that this should be different?
> Script to setup HTTPs for flight-service-www

- builders/flight-desktop-restapi/config/projects/flight-desktop-restapi.rb
- builders/flight-desktop-webapp/config/projects/flight-desktop-webapp.rb
This PR adds upper bounds to the dependencies of `flight-desktop-restapi` and `flight-desktop-webapp`.
@ColonelPanicks / @mjtko I didn't want to commit these changes to master whilst #21 is still a WIP.  Let me know if you want me to do so.
> Add upper dependency bounds to flight-desktop-*

- builders/flight-console-webapp/config/projects/flight-console-webapp.rb
- builders/flight-console-webapp/opt/flight/etc/service/types/console-webapp/configure.sh
- builders/flight-console-webapp/opt/flight/etc/www/server-https.d/console-02-webapp.conf
- builders/flight-desktop-webapp/config/projects/flight-desktop-webapp.rb
- builders/flight-desktop-webapp/opt/flight/etc/service/types/desktop-webapp/configure.sh
- builders/flight-desktop-webapp/opt/flight/etc/www/server-https.d/desktop-webapp.conf
- builders/flight-nodejs/config/software/flight-nodejs.rb
This PR adds support for an "unconfigured" state to the console and desktop webapps.  If the webapps are unable to load their configuration, i.e., the request results in a 404, they are in an unconfigured state.  An unconfigured webapp displays a "configure me" dashboard.
Hoops are jumped through to ensure that they can be configured for the first time, and to ensure that a non-existent config does indeed result in a 404.
This PR also contains a fix for the nodejs builder.  The details of which are in the commit message of  https://github.com/openflighthpc/openflight-omnibus-builder/commit/546fb961faaf32b0d76ca7dab2269ddad9a463d3.  @mjtko I think the solution I've taken here is the right approach, its certainly the simplest.  Would you mind taking a quick look and confirming that there …
> Flight console configure page

- builders/flight-desktop-restapi/config/projects/flight-desktop-restapi.rb
- builders/flight-desktop-restapi/opt/flight/etc/service/types/desktop-restapi/restart.sh
The issue preventing the restart has been resolved by closing the file descriptor:
https://github.com/openflighthpc/flight-desktop-restapi/pull/40
The PR has been merged as I needed the tag to build off and it was relatively small. Apparently I fixed some but not all of the dependabot issues.
> Reinstate the flight-desktop-restapi restart.sh script

- builders/flight-user-suite/build.sh
- builders/flight-user-suite/deb/control.tpl
- builders/flight-user-suite/rpm/flight-user-suite.spec
* Bump version to `2020.3`.
* Add `flight-job` and `flight-howto`.
* Update minimum version for `flight-runway` and `flight-starter`.
> Bump flight-user-suite

- builders/flight-runway/config/projects/flight-runway.rb
- builders/flight-runway/config/software/flight-runway.rb
- builders/flight-runway/config/software/openssl.rb
- builders/flight-runway/config/software/ruby.rb
Previously `flight-runway` was compiled with its own version of `OpenSSL`. AFAICS this is a legacy design decision back when the builder repo was forked from `omnibus-software` (or something to that affect).
I can see in the `config/projects/flight-runway.rb` there is some special casing for `openssl` on centos8, however this is not sufficient. There are a bunch of libraries (`pam`, `sudo`, `libkrb5`, `letsencrypt`, etc etc) which assume particular versions of `libcrypto.so.1.1`.
These assumptions work fine when the package manager controls the version of `openssl`, however they start to fail with out version. For example, an update to `libk5crypto.so.3` hobbled the flight ecosystem on `centos8`.
Instead of trying special case all the times `libcrypto.so.1.1` is used, a system dependency …
> Use the system version of OpenSSL on Centos8

- builders/flight-headnode-landing-page/.bundle/config
- builders/flight-headnode-landing-page/.gitignore
- builders/flight-headnode-landing-page/Gemfile
- builders/flight-headnode-landing-page/Gemfile.lock
- builders/flight-headnode-landing-page/LICENSE.txt
- builders/flight-headnode-landing-page/README.md
- builders/flight-headnode-landing-page/config/projects/flight-headnode-landing-page.rb
- builders/flight-headnode-landing-page/config/software/enforce-flight-runway.rb
- builders/flight-headnode-landing-page/config/software/flight-headnode-landing-page.rb
- builders/flight-headnode-landing-page/omnibus.rb
- builders/flight-headnode-landing-page/package-scripts/flight-headnode-landing-page/postinst
- builders/flight-headnode-landing-page/resources/flight-headnode-landing-page/deb/control.erb
- builders/flight-headnode-landing-page/resources/flight-headnode-landing-page/rpm/spec.erb
- builders/flight-www/config/projects/flight-www.rb
- builders/flight-www/config/software/flight-landing-page.rb
The `flight-www` package now depends on a virtual `flight-landing-page-content` package.  Currently there is a single package providing that: `flight-headnode-landing-page`.
The `flight-www` builder has been updated to include on the "mechanism" from the `flight-landing-page` git repo.
The `flight-headnode-landing-page` is built from the `flight-landing-page` git repo and pulls in just the headnode content.  When more landing page types are added, the builders for them will be *very* similar to the builder for `flight-headnode-landing-page`.  At that time, we will want to see if we can make the `flight-headnode-landing-page` builder a generic builder which builds multiple landing page content packages.  Or perhaps we do away with omnibus and use RPM and DEB directly.
> Separate landing page content from flight-www package

- builders/flight-pdsh/config/projects/flight-pdsh.rb
- builders/flight-pdsh/opt/flight/etc/flight-config-map.d/pdsh.yaml
- builders/flight-pdsh/opt/flight/etc/profile.d/90-pdsh.csh
- builders/flight-pdsh/opt/flight/etc/profile.d/90-pdsh.sh
- builders/flight-pdsh/resources/flight-pdsh/rpm/spec.erb
- builders/flight-starter/build.sh
- builders/flight-starter/rpm/flight-starter.spec
The `flight-pdsh` utility by default is added to the start of the `PATH` which overrides the system version. Instead it can be added to the end of the path with:
```
flight config set pdsh.priority system
```
Or it can be disabled with:
```
flight config set pdsh.priority disabled
```
> Allow flight-pdsh to respect the system version

- builders/flight-pdsh/config/projects/flight-pdsh.rb
- builders/flight-pdsh/package-scripts/flight-pdsh/postinst
The genders file may exist before installing `flight-pdsh` and should not be modified. An empty genders file should only be added if missing.
> Only create a genders file in flight-pdsh if missing

- builders/flight-action-api-estate/config/projects/flight-action-api-estate.rb
- builders/flight-action-api-power/config/projects/flight-action-api-power.rb
- builders/flight-action-api/config/projects/flight-action-api.rb
`flight-action-api-estate` has been downgraded as those changes are not yet ready for release.
Fixes the early merge of #63
> Bump flight-action-api{,-power}

- builders/flight-console-api/config/projects/flight-console-api.rb
- builders/flight-file-manager-api/config/projects/flight-file-manager-api.rb
- builders/flight-file-manager-api/config/software/enforce-flight-nodejs.rb
- builders/flight-nodejs/config/projects/flight-nodejs.rb
It now follows the same versioning used upstream.  That is, `flight-nodejs-12.16.3` installs nodejs version 12.16.3.  The `flight-js-system` has been updated to allow packages to depend on the new versioning scheme.
> Rework nodejs version numbering

- builders/flight-job-script-api/config/projects/flight-job-script-api.rb
- builders/flight-job-script-api/config/software/flight-job-script-api.rb
- builders/flight-job-script-webapp/config/projects/flight-job-script-webapp.rb
* Better handling of example script installation.
* Ensure `sbatch` is on PATH when submitting script.
> New version of flight-job-script-*

- builders/flight-console-webapp/omnibus.rb
- builders/flight-desktop-webapp/omnibus.rb
- builders/flight-file-manager-webapp/omnibus.rb
- builders/flight-job-script-webapp/config/projects/flight-job-script-webapp.rb
- builders/flight-job-script-webapp/omnibus.rb
* Update `flight-job-script-webapp` to use `flight-webapp-components`
* Fix typos in directories used in omnibus builds.  These typos do not bleed through to the RPMs.
> Job script webapp auth

- share/config/software/update_puma_scripts.rb
The various `puma` services use almost the exact same set of service scripts. However the process of copying them from project to project has started to introduce differences.
This PR implements a software definition which will update the `puma` config on each build. In practice they should rarely change, so the build will fail if they are updated. This is to allow the update to be checked into the repo.
If it is found a particular service needs a different set of scripts, then it will need to be managed independently. These cases should be carefully considered, as it has not been required for a fair amount of time.
> Add a shared config file for generating puma scripts

- builders/flight-desktop/config/projects/flight-desktop.rb
- builders/flight-desktop/opt/flight/libexec/commands/desktop
The previous `1.4.0.bX` release series was made in error, this is actually going to become part of the `1.5.0` release
> Rolling PR for flight-desktop to version 1.5.0-cX

- builders/flight-action-api/config/projects/flight-action-api.rb
- builders/flight-action-api/package-scripts/flight-action-api/postinst
The `jwt_secret` is now set using the non-interactive version of `flight service configure`.
The old value is respected if it has been already set. However the configure script is always ran so it can update the internal `action-api` config.
> Use the non-interactive configure in flight-action-api

- builders/flight-console-api/opt/flight/etc/www/server-https.d/console-01-api.conf
- builders/flight-desktop-restapi/opt/flight/etc/www/server-https.d/flight-desktop.conf
- builders/flight-file-manager-api/opt/flight/etc/www/server-https.d/file-manager-api.conf
- builders/flight-job-script-api/opt/flight/etc/www/server-https.d/job-script-api.conf
- builders/flight-login-api/opt/flight/etc/www/server-https.d/login-api.conf
- builders/flight-www/config/projects/flight-www.rb
- builders/flight-www/opt/flight/etc/service/types/www/configure.sh
Previously, it was possible to configure the HTTPS port used by Flight WWW.  However, using a port other than `443`broke our web suite.
* Redirecting from HTTP - > HTTPS always redirected to `443`.
* Flight File Manager API always tried to connect to the cloudcmd backend on port `443` as Sinatra's `request.port` was not detecting the correct port.  Flight WWW now adds a custom header to allow us to work around that.
These are both now fixed.
New builds of `flight-www` and `flight-file-manager-api` are required.  The other apps have had the fix applied, but as they didn't exhibit the bug do not require a new release.
> Fix configuring www https port

- builders/flight-headnode-landing-page/Gemfile
- builders/flight-headnode-landing-page/Gemfile.lock
- builders/flight-headnode-landing-page/config/projects/flight-headnode-landing-page.rb
- builders/flight-headnode-landing-page/config/software/flight-headnode-landing-page.rb
- builders/flight-headnode-landing-page/package-scripts/flight-headnode-landing-page/postinst
- builders/flight-www/config/projects/flight-www.rb
- builders/flight-www/dist/nginx.conf.tpl
- builders/flight-www/opt/flight/etc/www/mime.types
- builders/flight-www/opt/flight/etc/www/server-https.d/downloads.conf
A new `/downloads` route has been added to `nginx` which serves file with `Content-Disposition: attachment`.
It also packages the landing page with support for `config-packs`. The files to be downloaded for each config pack should be stored as:
`/opt/flight/usr/share/www/config-packs/<pack-name>/<filename>`
The MIME type/`Content-Type` is inferred from the file extension. By default, `nginx` does not support `text/markdown`. Instead the `mime.type` file has been duplicated into `/opt/flight/etc/www` with the new entry markdown entry.
As the `/downloads` route is a new feature, the system versions have been bumped to `-system-1.1`. The packages still provide the old `-system-1.0` for backwards compatibility.
> Add a nginx location to download files

- .env
- builders/flight-file-manager-api/config/projects/flight-file-manager-api.rb
- builders/flight-file-manager-api/config/software/flight-file-manager-api.rb
- builders/flight-file-manager-api/opt/flight/etc/service/env/file-manager-api
- builders/flight-login-api/config/projects/flight-login-api.rb
- builders/flight-login-api/config/software/flight-login-api.rb
- builders/flight-login-api/opt/flight/etc/service/types/login-api/configure.sh
- builders/flight-starter/build.sh
- builders/flight-starter/deb/control.tpl
- builders/flight-starter/rpm/flight-starter.spec
- builders/flight-web-suite-utils/.bundle/config
- builders/flight-web-suite-utils/.gitignore
- builders/flight-web-suite-utils/Gemfile
- builders/flight-web-suite-utils/Gemfile.lock
- builders/flight-web-suite-utils/LICENSE.txt
- builders/flight-web-suite-utils/README.md
- builders/flight-web-suite-utils/config/projects/flight-web-suite-utils.rb
- builders/flight-web-suite-utils/omnibus.rb
- builders/flight-web-suite-utils/opt/flight/etc/flight-config-map.d/web-suite.yaml
- builders/flight-web-suite-utils/resources/flight-web-suite-utils/deb/control.erb
- builders/flight-web-suite-utils/resources/flight-web-suite-utils/rpm/spec.erb
- builders/flight-web-suite/deb/control.tpl
- builders/flight-web-suite/rpm/flight-web-suite.spec
- builders/flight-www/config/projects/flight-www.rb
- builders/flight-www/config/software/flight-cert.rb
- builders/flight-www/package-scripts/flight-www/postinst
EDIT: Original PR description
I need the ability to generate alpha release packages for the `flight-web-suite` domain  changes.
`omnibus` already supports building of branches/commit hashes, so all that is needed is a way to hook in the required value. This means tagging the upstream repo is not required when generating a dev build.
---
In addition to the `alpha` release mechanism, both `login-api` and `file-manager-api` have been updated to use the new `FlightConfiguration::DSL` with a `Flight` stub.
This means the core configuration is now stored within `/opt/flight/etc` and various files within `/opt/flight/{libexec,var}`. Most of the config overrides within the builder have been removed; as they reconfigured the paths to `/opt/flight/...`. This is now done implicitly by the `Flight` …
> Update file-manager-api and login-api to use the new configuration mechanism

- builders/flight-scheduler-controller/config/projects/flight-scheduler-controller.rb
- builders/flight-scheduler-controller/opt/flight/etc/service/types/scheduler-controller/restart.sh
- builders/flight-scheduler-controller/opt/flight/etc/service/types/scheduler-controller/start.sh
- builders/flight-scheduler-controller/opt/flight/etc/service/types/scheduler-controller/stop.sh
- builders/flight-scheduler-controller/opt/flight/opt/scheduler-controller/bin/start
Based on #68
Canonically the `falcon` web server relies on a controller process to be responsible for starting/stopping/restarting it. As such the infrastructure underpinning `falcon-get-pid` is designed to return the parent process identifier (PPID) not the PID.
In the context of `flight-scheduler-controller`, the PPID is a bash wrapper script (`bin/start`) which does not provide the same "controller" functionality `falcon` is expecting. This can causes various issues if the wrapper exits without the `falcon` daemon being killed (such as the PPID/PID becoming 1).
It has proven to be a difficult task to get the PID through the `get-falcon-pid` script/infrastructure and as such it has been removed. Instead the service `start`/`stop`/`restart` scripts have been remodelled to behaviour …
> Remove falcon-get-pid from the scheduler-controller scripts

- builders/flight-file-manager-api/config/software/flight-file-manager-backend.rb
This PR makes two changes:
* Only install the production libraries, and
* Remove various `dev` directories
> Remove dev files from file-manager-api builds

- builders/flight-runway/config/projects/flight-runway.rb
- builders/flight-runway/config/software/cacerts.rb
cacerts needs updating to fix an issue with Centos7 detailed at https://blog.devgenius.io/rhel-centos-7-fix-for-lets-encrypt-change-8af2de587fe4 (further details at https://docs.certifytheweb.com/docs/kb/kb-202109-letsencrypt/ and https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/).
The most recent version of the cacerts software definition has been copied from the omnibus-software github repo.  This is sufficient to update cacerts and avoids potentially updating all of the software used in flight-runway.
> Update cacerts software definition

- builders/flight-headnode-landing-page/config/projects/flight-headnode-landing-page.rb
- builders/flight-headnode-landing-page/package-scripts/flight-headnode-landing-page/postinst
This PR comments out the symbolic link line in the post-installation script which was previously enabling the `example.md.disabled` config pack. It also adjusts the comment above the 'enable' clause describing how to enable it.
> Stop enabling the example config pack during post-installation script

- builders/flight-desktop/contrib/howto/1.8
This PR updates the `flight-desktop` documentation to describe usage of a new CLI parameter introduced in https://github.com/openflighthpc/flight-desktop/pull/40.
> Describe environment override parameter for flight desktop

- builders/flight-file-manager-api/config/projects/flight-file-manager-api.rb
- builders/flight-file-manager-api/opt/flight/etc/www/server-https.d/file-manager-api.conf
- builders/flight-www/config/projects/flight-www.rb
- builders/flight-www/dist/nginx.conf.tpl
- builders/flight-www/opt/flight/etc/www/error-locations.conf
- builders/flight-www/opt/flight/etc/www/http.d/base-http.conf
- builders/flight-www/opt/flight/etc/www/http.d/https.conf.disabled
This PR adds a line to an nginx config file under `flight-file-manager-api`. It sets the maximum file upload size to 50MB.
> Limit file manager api file upload size to 50M

- builders/flight-headnode-landing-page/config/projects/flight-headnode-landing-page.rb
- builders/flight-headnode-landing-page/config/software/enforce-flight-nodejs.rb
- builders/flight-headnode-landing-page/config/software/flight-headnode-landing-page.rb
- builders/flight-headnode-landing-page/config/software/flight-webapp-components.rb
This PR is part of a group of PRs which aim to create a static version of the account menu from `flight-webapp-components` and include this static version on `flight-landing-page`.
This PR adds to the `flight-headnode-landing-page` builder to include the newly created account menu build created in https://github.com/openflighthpc/flight-webapp-components/pull/8.
NB: The Github paths used in this PR's Omnibus files refer to feature branches, and will need to be changed to a version number prior to merging.
> Add webapp components login menu to Landing Page

- Vagrantfile
- vagrant/provision.sh
This PR adds a new build definition to the `Vagrantfile` for use in building packages for the Centos Stream 9 platform.
Work was required to get RVM/Ruby 2.7 working. Ruby 2.7 (and any subsequent use of `rubygems`) depends on OpenSSL 1.1. OpenSSL 1.1 does not exist in the Centos Stream 9 repositories (it ships with OpenSSL 3.0).
The `vagrant/provision.sh` file has had extra steps added to it to:
- Download the OpenSSL 1.1 source
- Compile the source to `/opt/openssl-1.1.1t`
- Link the system SSL certificates to OpenSSL 1.1.1
- Install Ruby 2.7, pointing it at the newly compiled OpenSSL 1.1.1
Once the extra steps are complete, the virtual machine is ready to build packages out of the box.
> Centos Stream 9 builder

- builders/flight-console-api/config/projects/flight-console-api.rb
- builders/flight-console-api/package-scripts/flight-console-api/postinst
SSH-RSA is deprecated, so we use ECDSA now.
> Use different SSH key type in console-api for RH9

- Vagrantfile
- vagrant/provision.sh
Centos 8 has now reached EOL and no longer receives development resources from the official CentOS proect. We are now using the `vault.centos.org` repos. The logic to switch repos is added both in the provisioning script and in the `vagrant-vbguest` installer hooks, as the latter is executed prior to the provisioning script (but not always executed at all).
> Fix Centos 8 mirrors

- Vagrantfile
This PR adds some static privately-networked IP addresses to the build machine definitions. I've also removed some old, unused Ubuntu build machines. This is part of some upcoming work to further automate/streamline package-building on multiple platforms.
> Add IPs to build machines

- builders/flight-user-suite/build.sh
- builders/flight-user-suite/deb/control.tpl
- builders/flight-user-suite/rpm/flight-user-suite.spec
This PR introduces a weak dependency on `flight-plugin-system-starter` for Flight User Suite on all available platforms (all except EL7). These platforms will now prefer `flight-plugin-system-starter` over `flight-plugin-manual-starter`.
> Flight User Suite plugin dependency

- builders/flight-console-api/config/projects/flight-console-api.rb
- builders/flight-console-api/opt/flight/opt/console-api/etc/config.json
- builders/flight-console-api/package-scripts/flight-console-api/postinst
- builders/flight-console-api/package-scripts/flight-console-api/stubs/postinst-configure
Flight Console API has been updated to generate `ecdsa` keys instead of `ssh-rsa` keys.
> Use ECDSA key instead of RSA in Console API

- builders/flight-hunter/opt/flight/etc/banner/banner.d/20-hunter-status.sh
- builders/flight-hunter/opt/flight/etc/banner/tips.d/30-hunter.rc
- builders/flight-hunter/opt/flight/etc/settings.d/hunter.rc
- builders/flight-profile/config/projects/flight-profile.rb
- builders/flight-profile/opt/flight/etc/banner/banner.d/21-profile-status.sh
- builders/flight-profile/opt/flight/etc/banner/tips.d/40-profile.rc
- builders/flight-profile/opt/flight/etc/settings.d/profile.rc
Requires https://github.com/openflighthpc/flight-starter/pull/17 (for all) and https://github.com/openflighthpc/flight-profile/pull/124 (for profile banner)
This adds additional files to Profile & Hunter builders to add banner messages with current status of profile queue and hunter queue. It also adds these two commands to the TIPS menu in the banner.
Example when `flight set hunter on` and `flight set profile on` have been run:
> Add Profile & Hunter to Banner & Tips

- builders/flight-plugin-systemd-service/dist/flight-service.service
This is based on the branch [`release/web-suite-overhaul`](https://github.com/openflighthpc/openflight-omnibus-builder/tree/release/web-suite-overhaul). 
Adds cloud services to systemd service file such that Flight Service will behave properly in environments where those services exist.
> Cloud dependencies for Flight Service

- share/config/software/update_puma_scripts.rb
Occasionally, APIs that we package (the motivation for this PR being Flight Profile API) take longer than the initially estimated 10 seconds for Puma to become responsive. Flight Profile API has been recorded taking roughly 10.5 seconds, which, very inconveniently, is just above the value currently hard-coded into the Puma script templates. While work _could_ be done to let this value be configured by the project using the shared `update_puma_scripts` software, it is much simpler to update the hard-coded value to 15 seconds, in case this issue ever arises with other Flight APIs.
> Puma waits for 15 seconds instead of 10 seconds

- builders/flight-console-webapp/package-scripts/flight-console-webapp/postinst
- builders/flight-console-webapp/package-scripts/flight-console-webapp/postrm
- builders/flight-desktop-webapp/package-scripts/flight-desktop-webapp/postinst
- builders/flight-desktop-webapp/package-scripts/flight-desktop-webapp/postrm
- builders/flight-file-manager-webapp/package-scripts/flight-file-manager-webapp/postinst
- builders/flight-file-manager-webapp/package-scripts/flight-file-manager-webapp/postrm
- builders/flight-headnode-landing-page/package-scripts/flight-headnode-landing-page/postinst
- builders/flight-job-script-webapp/package-scripts/flight-job-script-webapp/postinst
- builders/flight-job-script-webapp/package-scripts/flight-job-script-webapp/postrm
- builders/flight-www/package-scripts/flight-www/postinst
- builders/flight-www/package-scripts/flight-www/postrm
This PR will redirect any occurrences of `landing-page compile` to a log file such that package installation process is not filled with spam but errors can still be located/addressed if occurring by referencing the log file. 
Additionally this PR includes a small fix for `flight-www` `postrm` where it was _trying_ to check that the process wasn't a removal (e.g. an upgrade) with incorrect logical operators (which would also cause a `[: ~!=: binary operator expected` in the event that the first argument is `0` [which is the case for RPM uninstalls])
> Output landing-page compile to file instead of stdout

- builders/flight-desktop/config/projects/flight-desktop.rb
This PR aims to address the inconsistency between Flight Desktop tool dependencies and the dependencies requested by the Flight Desktop packages.
In recent releases of Flight Desktop [`xorg-x11-apps` has been replaced with `ImageMagick`](https://github.com/openflighthpc/flight-desktop/pull/56) for screen capturing due to the former package being deprecated from EL9.
What I _hope_ these modifications do is add an optional dependency on ImageMagick (e.g. installed if found in repos but, if not, installation of flight desktop should go ahead). 
This change has also been made to debian so both will need to be tested (attempting to get a building system running to verify functionality). 
**Question: Does anything need to be done to flight-desktop-webapp as well?**
> Optional dependency on ImageMagick for screen capture
